(()=>{
  'use strict';
  const body=document.body, edition=body.dataset.edition, gold=edition==='binance';
  const accent=gold?'#f0b90b':'#b9f53c', canvas=document.querySelector('#matrix-rain'), ctx=canvas?.getContext('2d');
  const media=matchMedia('(prefers-reduced-motion: reduce)'), toggle=document.querySelector('#motion-toggle');
  let paused=false;try{paused=sessionStorage.getItem('404-preview-motion')==='paused';}catch{}
  let w=0,h=0,columns=[],frame=0,last=0;
  function resize(){if(!ctx)return;w=innerWidth;h=innerHeight;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);columns=Array.from({length:Math.ceil(w/28)},()=>({y:Math.random()*h,s:1+Math.random()*1.3}));ctx.fillStyle=gold?'#090a0b':'#080b08';ctx.fillRect(0,0,w,h);draw(true);}
  function draw(still=false){if(!ctx)return;ctx.fillStyle=gold?'rgba(9,10,11,.13)':'rgba(8,11,8,.13)';ctx.fillRect(0,0,w,h);ctx.font='11px monospace';columns.forEach((c,i)=>{if(still){for(let j=0;j<5;j++){ctx.fillStyle=j===0?accent:(gold?'#645020':'#385b29');ctx.fillText(Math.random()>.5?'0':'1',i*28,c.y-j*17);}}else{ctx.fillStyle=Math.random()>.96?(gold?'#fff2b8':'#e7ffc5'):accent;ctx.fillText(Math.random()>.5?'0':'1',i*28,c.y);c.y+=17*c.s;if(c.y>h+180)c.y=-Math.random()*400;}});}
  function tick(t){if(paused||media.matches||document.hidden){frame=0;return;}if(t-last>70){draw();last=t;}frame=requestAnimationFrame(tick);}
  function start(){if(!frame&&!paused&&!media.matches&&!document.hidden)frame=requestAnimationFrame(tick);}
  function sync(){body.classList.toggle('paused',paused);body.classList.toggle('reduced-motion',media.matches);toggle?.setAttribute('aria-pressed',String(paused));toggle?.setAttribute('aria-label',paused?'Resume visual effects':'Pause visual effects');toggle?.setAttribute('title',media.matches?'Reduced motion preference is active':paused?'Resume visual effects':'Pause visual effects');if(paused||media.matches){cancelAnimationFrame(frame);frame=0;}else start();}
  toggle?.addEventListener('click',()=>{paused=!paused;try{sessionStorage.setItem('404-preview-motion',paused?'paused':'playing');}catch{}sync();toast(paused?'Visual effects paused.':media.matches?'Reduced motion preference respected.':'Visual effects resumed.');});
  media.addEventListener('change',sync);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0;}else start();});
  let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(resize,120);});resize();sync();
  let toastTimer;function toast(message){const el=document.querySelector('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2500);}
  const art=document.querySelector('.hero-art');
  if(matchMedia('(pointer:fine)').matches){art?.addEventListener('pointermove',e=>{if(paused||media.matches)return;const r=art.getBoundingClientRect();art.style.setProperty('--px',`${((e.clientX-r.left)/r.width-.5)*10}px`);art.style.setProperty('--py',`${((e.clientY-r.top)/r.height-.5)*8}px`);});art?.addEventListener('pointerleave',()=>{art.style.setProperty('--px','0px');art.style.setProperty('--py','0px');});}
  const scanButtons=[...document.querySelectorAll('[data-scan]')], status=document.querySelector('#scan-status');let scanning=false;
  function scan(){if(scanning)return;scanning=true;body.classList.add('scanning');scanButtons.forEach(b=>{b.disabled=true;});status?.classList.remove('success');if(status)status.textContent=gold?'DECRYPTING SUBJECT RECORD…':'SEARCHING FOR AN IDENTITY…';setTimeout(()=>{if(status)status.textContent=gold?'404 / DECRYPTED. IDENTITY: NOT FOUND.':'404 / SIGNAL FOUND. IDENTITY: NOT FOUND.';status?.classList.add('success');document.querySelectorAll('[data-identity-result]').forEach(n=>{n.textContent='NOT FOUND';});body.classList.remove('scanning');scanButtons.forEach(b=>{b.disabled=false;});scanning=false;toast('The file exists. The identity doesn’t.');},media.matches?120:1300);}
  scanButtons.forEach(b=>b.addEventListener('click',scan));
  const aliases=gold?['vault_0x404','cipher.null','unlisted_404','ghost.key']:['ghost_0x404','anonymous.exe','signal.null','unlisted_404'];let ai=0;
  function mask(){ai=(ai+1)%aliases.length;document.querySelectorAll('[data-alias]').forEach(n=>n.textContent=aliases[ai]);toast(`Alias rotated: ${aliases[ai]}`);return aliases[ai];}
  document.querySelectorAll('[data-mask]').forEach(b=>b.addEventListener('click',mask));
  const output=document.querySelector('#terminal-output'),form=document.querySelector('#terminal-form'),input=document.querySelector('#terminal-input');
  function line(text,kind=''){const el=document.createElement('div');el.className=`terminal-line ${kind}`;el.textContent=text;output?.append(el);while(output&&output.children.length>45)output.firstElementChild.remove();if(output)output.scrollTop=output.scrollHeight;}
  function run(raw){const command=String(raw).trim().toLowerCase();if(!command)return;line(`> ${command}`,'muted');switch(command){case'help':line('whoami   — search the identity');line('mask     — rotate the alias');line(gold?'decrypt  — open the vault record':'trace    — follow the signal');line('lore     — read the origin');line('clear    — clear this terminal');break;case'whoami':line('Searching registry…','muted');line('404: IDENTITY_NOT_FOUND','accent');break;case'mask':line(`Alias: ${mask()}`,'accent');line('New mask. Same absence.');break;case'trace':line('signal → fragment → null','accent');line('You found the signal. Not the source.');break;case'decrypt':line('FILE: OPEN / OWNER: UNKNOWN','accent');line('A thousand records. Not a single face.');break;case'lore':line(gold?'Every vault keeps a record. This one lost the owner.':'Every system wants a name. 404 leaves a signal.','accent');line('No name. No face. No identity.');break;case'clear':if(output)output.replaceChildren();line('404 shell ready. Type help.','muted');break;default:line('Unknown command. Try help.','muted');}if(input)input.value='';}
  form?.addEventListener('submit',e=>{e.preventDefault();run(input?.value||'');});document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>run(b.dataset.command)));
  const files=gold?{
    identity:{title:'01 / THE MISSING OWNER',heading:'A file without a face.',text:'The vault remembers every transaction. Every movement. Every trace. Then one record appeared with nothing where a name should be.',code:'SUBJECT  404\nOWNER    [REDACTED]\nFACE     NULL\nSTATUS   UNRESOLVED'},
    origin:{title:'02 / THE FIRST FRAGMENT',heading:'Nobody signed the file.',text:'No introduction. No photograph. No origin story the system could verify. Just three digits, glowing in a place that was supposed to be empty.',code:'ENTRY    UNKNOWN\nSOURCE   [REDACTED]\nSIGNAL   PRESENT\nAUTHOR   NOT FOUND'},
    signal:{title:'03 / THE SIGNAL REMAINS',heading:'Erase the name. Keep the signal.',text:'404 is a shared disguise. A character anyone can become, and a story nobody can own. The file stays open. The identity stays missing.',code:'ALIAS    ROTATING\nACCESS   OPEN\nIDENTITY NOT FOUND\nSTORY    CONTINUING'}
  }:{};
  const tabs=[...document.querySelectorAll('[data-file]')];function select(tab){const file=files[tab.dataset.file];if(!file)return;tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;});document.querySelector('#file-panel')?.setAttribute('aria-labelledby',tab.id);for(const [id,value]of Object.entries({'file-kicker':file.title,'file-heading':file.heading,'file-story':file.text,'file-code':file.code})){const node=document.getElementById(id);if(node)node.textContent=value;}}
  tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>select(tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight'||e.key==='ArrowDown')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')next=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();select(tabs[next]);tabs[next].focus();});});
  if('IntersectionObserver'in window&&!media.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));body.classList.add('enhanced');}
})();
